// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaiqNas3Z_lJhYTDgzFhQiBMPBZgZJ3mg',
    appId: '1:279211396950:web:62545b4d64ca1a00cb50f7',
    messagingSenderId: '279211396950',
    projectId: 'fir-learning-6b4a6',
    authDomain: 'fir-learning-6b4a6.firebaseapp.com',
    storageBucket: 'fir-learning-6b4a6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6CozGbnPV_85l4toRaNO4ZCR2w_VKPho',
    appId: '1:279211396950:android:8983d45588015b6dcb50f7',
    messagingSenderId: '279211396950',
    projectId: 'fir-learning-6b4a6',
    storageBucket: 'fir-learning-6b4a6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaiqNas3Z_lJhYTDgzFhQiBMPBZgZJ3mg',
    appId: '1:279211396950:web:a43e763f0601d20bcb50f7',
    messagingSenderId: '279211396950',
    projectId: 'fir-learning-6b4a6',
    authDomain: 'fir-learning-6b4a6.firebaseapp.com',
    storageBucket: 'fir-learning-6b4a6.firebasestorage.app',
  );
}
